# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/links2news',
                'doc_host': 'https://michaeldini.github.io',
                'git_url': 'https://github.com/michaeldini/links2news',
                'lib_path': 'links2news'},
  'syms': { 'links2news.mittech': {'links2news.mittech.get_soup': ('mittech.html#get_soup', 'links2news/mittech.py')},
            'links2news.nature': {'links2news.nature.get_soup': ('nature.html#get_soup', 'links2news/nature.py')}}}
