# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/links2news',
                'doc_host': 'https://michaeldini.github.io',
                'git_url': 'https://github.com/michaeldini/links2news',
                'lib_path': 'links2news'},
  'syms': {'links2news.links2news': {'links2news.links2news.get_soup': ('nature.html#get_soup', 'links2news/links2news.py')}}}
